add_newline = false

format = """
$hostname\
$directory\
$git_branch\
$git_status\
$character\
"""


[cmd_duration]
disabled = false
min_time = 5_000

[character]
success_symbol = "[➜](bold cyan)"
error_symbol = "[✗](bold red)"



[hostname]
ssh_only=false


[time]
disabled = false
use_12hr = true
